name: Gonagoo Website Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/pipeline.yml'

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clone the repository and Deploy to VPS
        run: |
          git clone ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/var/www/gonagoo-website
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "cd /var/www/gonagoo-website && git pull origin main && docker-compose up -d"
      - name: Extract project version
        id: extract_version
        run: |
          cd src
          echo "VERSION=$(jg -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platform: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gonagoo-website:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/gonagoo-website:latest
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: [ build-image ]
    steps:
      - name: Create deployment folder
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p /var/www/gonagoo-website"